/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

declare module "@elegant-router/types" {
  type ElegantConstRoute = import('@elegant-router/vue').ElegantConstRoute;

  /**
   * route layout
   */
  export type RouteLayout = "base" | "blank";

  /**
   * route map
   */
  export type RouteMap = {
    "root": "/";
    "not-found": "/:pathMatch(.*)*";
    "403": "/403";
    "404": "/404";
    "500": "/500";
    "banners": "/banners";
    "banners_form": "/banners/form";
    "banners_list": "/banners/list";
    "coupons": "/coupons";
    "coupons_list": "/coupons/list";
    "coupons_templates": "/coupons/templates";
    "coupons_templates_form": "/coupons/templates/form";
    "coupons_templates_list": "/coupons/templates/list";
    "dashboard": "/dashboard";
    "files": "/files";
    "files_list": "/files/list";
    "iframe-page": "/iframe-page/:url";
    "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?";
    "luckywheel": "/luckywheel";
    "luckywheel_prizes": "/luckywheel/prizes";
    "luckywheel_prizes_form": "/luckywheel/prizes/form";
    "luckywheel_prizes_list": "/luckywheel/prizes/list";
    "luckywheel_records": "/luckywheel/records";
    "luckywheel_records_list": "/luckywheel/records/list";
    "membertiers": "/membertiers";
    "membertiers_form": "/membertiers/form";
    "membertiers_list": "/membertiers/list";
    "orders": "/orders";
    "orders_detail": "/orders/detail";
    "orders_list": "/orders/list";
    "payments": "/payments";
    "payments_list": "/payments/list";
    "points": "/points";
    "points_categories": "/points/categories";
    "points_form": "/points/form";
    "points_list": "/points/list";
    "products": "/products";
    "products_categories": "/products/categories";
    "products_form": "/products/form";
    "products_list": "/products/list";
    "settings": "/settings";
    "settings_avatars": "/settings/avatars";
    "settings_business": "/settings/business";
    "settings_logistics": "/settings/logistics";
    "settings_map": "/settings/map";
    "settings_pay": "/settings/pay";
    "settings_printer": "/settings/printer";
    "settings_storage": "/settings/storage";
    "settings_store": "/settings/store";
    "shop": "/shop";
    "shop_categories": "/shop/categories";
    "shop_orders": "/shop/orders";
    "shop_orders_detail": "/shop/orders/detail";
    "shop_orders_list": "/shop/orders/list";
    "shop_products": "/shop/products";
    "shop_products_form": "/shop/products/form";
    "shop_products_list": "/shop/products/list";
    "users": "/users";
    "users_list": "/users/list";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * route path
   */
  export type RoutePath = RouteMap[RouteKey];

  /**
   * custom route key
   */
  export type CustomRouteKey = Extract<
    RouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the generated route key
   */
  export type GeneratedRouteKey = Exclude<RouteKey, CustomRouteKey>;

  /**
   * the first level route key, which contain the layout of the route
   */
  export type FirstLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "banners"
    | "coupons"
    | "dashboard"
    | "files"
    | "iframe-page"
    | "login"
    | "luckywheel"
    | "membertiers"
    | "orders"
    | "payments"
    | "points"
    | "products"
    | "settings"
    | "shop"
    | "users"
  >;

  /**
   * the custom first level route key
   */
  export type CustomFirstLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the last level route key, which has the page file
   */
  export type LastLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "iframe-page"
    | "login"
    | "banners_form"
    | "banners_list"
    | "coupons_list"
    | "coupons_templates_form"
    | "coupons_templates_list"
    | "dashboard"
    | "files_list"
    | "luckywheel_prizes_form"
    | "luckywheel_prizes_list"
    | "luckywheel_records_list"
    | "membertiers_form"
    | "membertiers_list"
    | "orders_detail"
    | "orders_list"
    | "payments_list"
    | "points_categories"
    | "points_form"
    | "points_list"
    | "products_categories"
    | "products_form"
    | "products_list"
    | "settings_avatars"
    | "settings_business"
    | "settings_logistics"
    | "settings_map"
    | "settings_pay"
    | "settings_printer"
    | "settings_storage"
    | "settings_store"
    | "shop_categories"
    | "shop_orders_detail"
    | "shop_orders_list"
    | "shop_products_form"
    | "shop_products_list"
    | "users_list"
  >;

  /**
   * the custom last level route key
   */
  export type CustomLastLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the single level route key
   */
  export type SingleLevelRouteKey = FirstLevelRouteKey & LastLevelRouteKey;

  /**
   * the custom single level route key
   */
  export type CustomSingleLevelRouteKey = CustomFirstLevelRouteKey & CustomLastLevelRouteKey;

  /**
   * the first level route key, but not the single level
  */
  export type FirstLevelRouteNotSingleKey = Exclude<FirstLevelRouteKey, SingleLevelRouteKey>;

  /**
   * the custom first level route key, but not the single level
   */
  export type CustomFirstLevelRouteNotSingleKey = Exclude<CustomFirstLevelRouteKey, CustomSingleLevelRouteKey>;

  /**
   * the center level route key
   */
  export type CenterLevelRouteKey = Exclude<GeneratedRouteKey, FirstLevelRouteKey | LastLevelRouteKey>;

  /**
   * the custom center level route key
   */
  export type CustomCenterLevelRouteKey = Exclude<CustomRouteKey, CustomFirstLevelRouteKey | CustomLastLevelRouteKey>;

  /**
   * the center level route key
   */
  type GetChildRouteKey<K extends RouteKey, T extends RouteKey = RouteKey> = T extends `${K}_${infer R}`
    ? R extends `${string}_${string}`
      ? never
      : T
    : never;

  /**
   * the single level route
   */
  type SingleLevelRoute<K extends SingleLevelRouteKey = SingleLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}$view.${K}`;
      }
    : never;

  /**
   * the last level route
   */
  type LastLevelRoute<K extends GeneratedRouteKey> = K extends LastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `view.${K}`;
      }
    : never;
  
  /**
   * the center level route
   */
  type CenterLevelRoute<K extends GeneratedRouteKey> = K extends CenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the multi level route
   */
  type MultiLevelRoute<K extends FirstLevelRouteNotSingleKey = FirstLevelRouteNotSingleKey> = K extends string
    ? ElegantConstRoute & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}`;
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;
  
  /**
   * the custom first level route
   */
  type CustomSingleLevelRoute<K extends CustomFirstLevelRouteKey = CustomFirstLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `layout.${RouteLayout}$view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom last level route
   */
  type CustomLastLevelRoute<K extends CustomRouteKey> = K extends CustomLastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom center level route
   */
  type CustomCenterLevelRoute<K extends CustomRouteKey> = K extends CustomCenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the custom multi level route
   */
  type CustomMultiLevelRoute<K extends CustomFirstLevelRouteNotSingleKey = CustomFirstLevelRouteNotSingleKey> =
    K extends string
      ? ElegantConstRoute & {
          name: K;
          path: RouteMap[K];
          component: `layout.${RouteLayout}`;
          children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
        }
      : never;

  /**
   * the custom route
   */
  type CustomRoute = CustomSingleLevelRoute | CustomMultiLevelRoute;

  /**
   * the generated route
   */
  type GeneratedRoute = SingleLevelRoute | MultiLevelRoute;

  /**
   * the elegant route
   */
  type ElegantRoute = GeneratedRoute | CustomRoute;
}
