/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  banners_form: () => import("@/views/banners/form/index.vue"),
  banners_list: () => import("@/views/banners/list/index.vue"),
  coupontemplates_form: () => import("@/views/couponTemplates/form/index.vue"),
  coupontemplates_list: () => import("@/views/couponTemplates/list/index.vue"),
  coupons_list: () => import("@/views/coupons/list/index.vue"),
  dashboard: () => import("@/views/dashboard/index.vue"),
  files_list: () => import("@/views/files/list/index.vue"),
  home: () => import("@/views/home/index.vue"),
  orders_detail: () => import("@/views/orders/detail/index.vue"),
  orders_list: () => import("@/views/orders/list/index.vue"),
  points_form: () => import("@/views/points/form/index.vue"),
  points_list: () => import("@/views/points/list/index.vue"),
  products_form: () => import("@/views/products/form/index.vue"),
  products_list: () => import("@/views/products/list/index.vue"),
  users_list: () => import("@/views/users/list/index.vue"),
};
