/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'banners',
    path: '/banners',
    component: 'layout.base',
    meta: {
      title: 'banners',
      i18nKey: 'route.banners'
    },
    children: [
      {
        name: 'banners_form',
        path: '/banners/form',
        component: 'view.banners_form',
        meta: {
          title: 'banners_form',
          i18nKey: 'route.banners_form'
        }
      },
      {
        name: 'banners_list',
        path: '/banners/list',
        component: 'view.banners_list',
        meta: {
          title: 'banners_list',
          i18nKey: 'route.banners_list'
        }
      }
    ]
  },
  {
    name: 'coupons',
    path: '/coupons',
    component: 'layout.base',
    meta: {
      title: 'coupons',
      i18nKey: 'route.coupons'
    },
    children: [
      {
        name: 'coupons_list',
        path: '/coupons/list',
        component: 'view.coupons_list',
        meta: {
          title: 'coupons_list',
          i18nKey: 'route.coupons_list'
        }
      },
      {
        name: 'coupons_templates',
        path: '/coupons/templates',
        component: 'layout.base',
        meta: {
          title: 'coupons_templates',
          i18nKey: 'route.coupons_templates'
        },
        children: [
          {
            name: 'coupons_templates_form',
            path: '/coupons/templates/form',
            component: 'view.coupons_templates_form',
            meta: {
              title: 'coupons_templates_form',
              i18nKey: 'route.coupons_templates_form'
            }
          },
          {
            name: 'coupons_templates_list',
            path: '/coupons/templates/list',
            component: 'view.coupons_templates_list',
            meta: {
              title: 'coupons_templates_list',
              i18nKey: 'route.coupons_templates_list'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'dashboard',
    path: '/dashboard',
    component: 'layout.base$view.dashboard',
    meta: {
      title: 'dashboard',
      i18nKey: 'route.dashboard'
    }
  },
  {
    name: 'files',
    path: '/files',
    component: 'layout.base',
    meta: {
      title: 'files',
      i18nKey: 'route.files'
    },
    children: [
      {
        name: 'files_list',
        path: '/files/list',
        component: 'view.files_list',
        meta: {
          title: 'files_list',
          i18nKey: 'route.files_list'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'membertiers',
    path: '/membertiers',
    component: 'layout.base',
    meta: {
      title: 'membertiers',
      i18nKey: 'route.membertiers'
    },
    children: [
      {
        name: 'membertiers_form',
        path: '/membertiers/form',
        component: 'view.membertiers_form',
        meta: {
          title: 'membertiers_form',
          i18nKey: 'route.membertiers_form'
        }
      },
      {
        name: 'membertiers_list',
        path: '/membertiers/list',
        component: 'view.membertiers_list',
        meta: {
          title: 'membertiers_list',
          i18nKey: 'route.membertiers_list'
        }
      }
    ]
  },
  {
    name: 'orders',
    path: '/orders',
    component: 'layout.base',
    meta: {
      title: 'orders',
      i18nKey: 'route.orders'
    },
    children: [
      {
        name: 'orders_detail',
        path: '/orders/detail',
        component: 'view.orders_detail',
        meta: {
          title: 'orders_detail',
          i18nKey: 'route.orders_detail'
        }
      },
      {
        name: 'orders_list',
        path: '/orders/list',
        component: 'view.orders_list',
        meta: {
          title: 'orders_list',
          i18nKey: 'route.orders_list'
        }
      }
    ]
  },
  {
    name: 'points',
    path: '/points',
    component: 'layout.base',
    meta: {
      title: 'points',
      i18nKey: 'route.points'
    },
    children: [
      {
        name: 'points_form',
        path: '/points/form',
        component: 'view.points_form',
        meta: {
          title: 'points_form',
          i18nKey: 'route.points_form'
        }
      },
      {
        name: 'points_list',
        path: '/points/list',
        component: 'view.points_list',
        meta: {
          title: 'points_list',
          i18nKey: 'route.points_list'
        }
      }
    ]
  },
  {
    name: 'products',
    path: '/products',
    component: 'layout.base',
    meta: {
      title: 'products',
      i18nKey: 'route.products'
    },
    children: [
      {
        name: 'products_form',
        path: '/products/form',
        component: 'view.products_form',
        meta: {
          title: 'products_form',
          i18nKey: 'route.products_form'
        }
      },
      {
        name: 'products_list',
        path: '/products/list',
        component: 'view.products_list',
        meta: {
          title: 'products_list',
          i18nKey: 'route.products_list'
        }
      }
    ]
  },
  {
    name: 'users',
    path: '/users',
    component: 'layout.base',
    meta: {
      title: 'users',
      i18nKey: 'route.users'
    },
    children: [
      {
        name: 'users_list',
        path: '/users/list',
        component: 'view.users_list',
        meta: {
          title: 'users_list',
          i18nKey: 'route.users_list'
        }
      }
    ]
  }
];
